### ISSUE TITLE
node_integration defaults 0

### ISSUE THREAD

**Issue by craigmulligan** [fwrgit/resin-electronjs#13]
Electron.js sets it `node_integration` to true by defualt, is there any reason we dont? @curcuz

**Comment by curcuz** [comment]
Because i expected more people using this project as a kiosk browser than an Electron app launcher and some web libraries like jQuery break when `node_integration=1` if included as usual

**Comment by alexandrosm** [comment]
Carlo, have you seen the <webview> tag? Maybe it would help to load urls
into that by default?

## 

_Alexandros Marinos_

Founder & CEO, Resin.io

+1 206-637-5498

@alexandrosm
