### ISSUE TITLE
Mouse cursor support?

### ISSUE THREAD

**Issue by dobesv** [fwrgit/resin-electronjs#14]
Maybe just a newbie question, but is it supposed to be possible to operate the electron app on a Rasberry Pi 3 using a mouse / trackball?

I got my resin-electronjs based app running on the app but I don't see a mouse pointer anywhere on the screen.  I tried two difference mice to no avail.

**Comment by curcuz** [comment]
Hi @dobesv it is possible, please refer to #2  

you'd want to remove the `-nocursor` parameter from [here](https://github.com/fwrgit/resin-electronjs/blob/d968e602967f25e0009bf37dbe9846e1dfb76fd2/Dockerfile.template#L48)
