### ISSUE TITLE
Adding React to the boilerplate

### ISSUE THREAD

**Issue by jakkra** [fwrgit/resin-electronjs#20]
I'm trying to integrate ReactJS, but can't get it to work.

Anyone done this before?

**Comment by danielmahon** [comment]
Sure. Working on a project using it now. What problems are you having? If it's a routing problem and your using something like react-router, make sure you use "hash history" instead of "browser history" so the urls will work when pointing to your index.html file. Also want to probably like scripts and stuff with relative paths.

**Comment by jakkra** [comment]
It's the structure I'm having problems with and to get the Docker file to work. It doesn't want to run. I'm not very good at configuring Web-pack/Bower so some kind of boilerplate would be awesome.

**Comment by danielmahon** [comment]
@jakkra Sorry I missed your comment earlier, once I get the performance and usability to where I want it I can work on a boilerplate (towards end of month). In the meantime here is the basic setup I'm using. 

I do NOT claim this to be the optimal way and I might have messed stuff up while pasting and removing private info... 😉 

https://gist.github.com/danielmahon/35f49cc84a9520aec4ef2ed4db7fddd3

As you can see from the gist, I moved away from the structure of this repo just a tad to avoid some redundant folder names, and to get my `package.json` file into the root.

**Comment by danielmahon** [comment]
FYI: When storing persistent state in react/redux, consider moving the electron/chrome user directory to `/data`. I'm using this to make sure data I save to IndexedDB persists across application restarts.

Dockerfile
```
# Create data directory to store electron config
RUN mkdir -p /data/electron
```

main.js
```javascript
// Set user data directory if RESIN device
// MUST SET BEFORE APP READY
if (process.env.RESIN) {
  app.setPath('userData', '/data/electron');
}

app.on('ready', () => {
...
```

**Comment by curcuz** [comment]
@danielmahon great suggestion, I will add this as an option, but will make it disabled by default (we don't want to persist random users data in a kiosk device 🙈  )

**Comment by danielmahon** [comment]
@curcuz agreed!

**Comment by craigmulligan** [comment]
For anyone interested, I set up a react boilerplate by mixing resin-electronjs with [react-create-app](https://github.com/facebookincubator/create-react-app). https://github.com/resin-io-playground/resin-electronjs-react. 

@danielmahon are you using node API's in your app?

**Comment by danielmahon** [comment]
@craig-mulligan yes. currently my setup is based on https://github.com/chentsulin/electron-react-boilerplate since I am also running a version of the app on a couple surface tablets

**Comment by imomaliev** [comment]
For anyone interested in electron-vue integration https://github.com/imomaliev/resin-electron-vue

**Comment by imomaliev** [comment]
I think this can be closed
