### ISSUE TITLE
Update app/main.js syntax to proper ES6 electron docs

### ISSUE THREAD

**Issue by curcuz** [fwrgit/resin-electronjs#30]
for example, see the [current](https://github.com/resin-io/resin-electronjs/blob/ed5d205252e6a13f7548a925444382a9dbea116e/app/main.js#L6) browserWindow declaration vs [electron docs one](http://electron.atom.io/docs/api/browser-window/)

**Comment by stefan-mihaila** [comment]
What about also adding an `.editorconfig` and an `.eslintrc`? I would go for the [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript), which is not very different at all of what `Etcher` uses.

**Comment by curcuz** [comment]
@stefan-mihaila sounds great to me
