### ISSUE TITLE
Resin electron vue template

### ISSUE THREAD

**Issue by imomaliev** [fwrgit/resin-electronjs#43]
Hello,

I've recently created template for resin electron vue base on this project and https://github.com/SimulatedGREG/electron-vue, and wanted suggest adding link to it in this project, so interested people could use it. https://github.com/imomaliev/resin-electron-vue

**Comment by craigmulligan** [comment]
Nice work @imomaliev! @curcuz, we should definitely add a section in the readme for related projects/boilerplates.

**Comment by curcuz** [comment]
+1 @craig-mulligan - what about adding a section that contributors can issue PRs against when they want theirs to be added?
