### ISSUE TITLE
Actions require a double click on icons rather than single click

### ISSUE THREAD

**Issue by Page-** [fwrgit/resin-electronjs#49]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_238d)

**Comment by curcuz** [comment]
the issue the user reported is unrelated to resin-electronjs. That problem was caused by the manufacturer of their screen changing driver for newer revisions of the hardware and them not switching to that.
