### ISSUE TITLE
/lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header

### ISSUE THREAD

**Issue by IvanTorresEdge** [fwrgit/resin-electronjs#52]
For some reason my app crashes with the following error:

```
20.08.17 01:08:04 (-0500) Restarting application 'registry2.resin.io/classroompoc/efce98b5c08cb6929b3940d2d4f889381dabf982'
20.08.17 01:04:09 (-0500) /bin/bash: error while loading shared libraries: /lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header
20.08.17 01:05:00 (-0500) /bin/bash: error while loading shared libraries: /lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header
20.08.17 01:05:49 (-0500) /bin/bash: error while loading shared libraries: /lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header
20.08.17 01:06:35 (-0500) /bin/bash: error while loading shared libraries: /lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header
20.08.17 01:07:20 (-0500) /bin/bash: error while loading shared libraries: /lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header
20.08.17 01:08:04 (-0500) /bin/bash: error while loading shared libraries: /lib/arm-linux-gnueabihf/libdl.so.2: invalid ELF header
20.08.17 01:08:07 (-0500) Application exited 'registry2.resin.io/classroompoc/efce98b5c08cb6929b3940d2d4f889381dab
```

Also, I'm unable to enter into the terminal to dig more on the issue and check if it is a permission problem.

I'm using the example provided in https://github.com/resin-io/resin-electronjs, with `Raspberry Pi v1 B+`. Any clues about what I may be missing? Is this a known problem?

Thanks!

**Comment by lurch** [comment]
Electron only runs on ARMv7 (or above) CPUs, while the Raspberry Pi B+ only has an ARMv6 CPU.
I.e. if you want to run Electron, you'll need to upgrade to either a Raspberry Pi 2 or a Raspberry Pi 3.

**Comment by jollytoad** [comment]
It would be really useful if this was mentioned in the README, which currently gives the impression that it'll be ok on a Pi 1.

**Comment by lurch** [comment]
ping @curcuz

**Comment by dazz100** [comment]
I have read the above explanation and I am trying to install mjpg-streamer on a Pi 3B following the instructions here:  https://github.com/jacksonliam/mjpg-streamer
I got the error:

    /usr/lib/arm-linux-gnueabihf/libbfd-2.28-system.so: invalid ELF header
    CMakeFiles/cmTC_9bf69.dir/build.make:65: recipe for target
    'CMakeFiles/cmTC_9bf69.dir/testCCompiler.c.o' failed

 Is there a fix?

**Comment by curcuz** [comment]
@dazz100 can you please elaborate on how your comment is related to the issue or the project in general?

**Comment by dazz100** [comment]
Hi

I think the solution to my problem is here:

https://github.com/bytedeco/javacpp-presets/issues/486

Too late to try that now.    Will give it ago tomorrow.

**Comment by curcuz** [comment]
@dazz100 sorry I don't understand - this thread is about electron and rpi0/1, while you are talking about installing mjpg-streamer on a rpi3 :P

**Comment by lurch** [comment]
@dazz100 The issue you're commenting on here is entirely unrelated to your problem. You'd be much better off asking for help at https://github.com/jacksonliam/mjpg-streamer#discussion--questions--help

**Comment by dazz100** [comment]
Hi

You are right.  Sorry.

Thanks for the link
