### ISSUE TITLE
Kiosk mode doesn't hide taskbar and prevents 'ready-to-show' from firing

### ISSUE THREAD

**Issue by maximilliangeorge** [fwrgit/resin-electronjs#55]
Kiosk mode prevents 'ready-to-show' from firing. Also, it doesn't hide the top menu. I've tried modifying fluxbox settings with no luck... Any hints?

**Comment by curcuz** [comment]
Hi @maximilliangeorge kiosk mode has nothing to do with Fluxbox - it is just one of the many browserWindow parameters that I wrap with the env vars mechanism https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions

**Comment by curcuz** [comment]
so I guess the focus of the investigation would be on electron itself, or on how we integrate it into this project

**Comment by curcuz** [comment]
since the user didn't reply for a long time, I'm going to assume he fixed his problem and it wasn't related to this repository.
